# Generated by Django 3.2.15 on 2022-08-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='state',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='country',
            new_name='district',
        ),
        migrations.AddField(
            model_name='register',
            name='account',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='materials',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
