# Generated by Django 3.2.15 on 2022-08-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20220814_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='country',
            new_name='district',
        ),
    ]
