# Generated by Django 3.2.15 on 2022-08-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_country_branch_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='account',
            field=models.CharField(choices=[('savings account', 'SAVINGS ACCOUNT'), ('current account', 'CURRENT ACCOUNT')], default='savings account', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('others', 'OTHERS')], default='male', max_length=200),
        ),
    ]
