# Generated by Django 3.2.15 on 2022-08-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20220814_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='materials',
        ),
        migrations.AddField(
            model_name='register',
            name='cheque',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='register',
            name='credit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='register',
            name='debit',
            field=models.BooleanField(default=True),
        ),
    ]
