# Generated by Django 3.2.13 on 2022-05-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table1',
            name='img',
            field=models.ImageField(default='cvbn', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
